serial-protocol: enable static API and remove StaticSerialProtocolDecoder typedef
as it is define in libsmp-static.h and this multiple definition causes
AVR toolchain with LTO enabled to fail with some MCUs, but not all.
For examples, targetting ATMega2560, we had this error:

lto1: internal compiler error: in splice_child_die, at dwarf2out.c:4905
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error:
xxx/arduino-1.8.6/hardware/tools/avr/bin/avr-gcc
returned 1 exit status
compilation terminated.
xxx/arduino-1.8.6/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld:
error: lto-wrapper failed
collect2: error: ld returned 1 exit status